            - name: Cloudflare Pages GitHub Action
  # You may pin to the exact commit or the version.
  # uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca
  uses: cloudflare/pages-action@v1.5.0
  with:
    # Cloudflare API Token
    apiToken: CLOUDFLARE_API_TOKEN
    # Cloudflare Account ID
    accountId: CLOUDFLARE_ACCOUNT_ID
    # The name of the Pages project to upload to
    projectName: prompt-us-pizzeria
    # The directory of static assets to upload
    directory: /
          
