- name: Cloudflare Pages GitHub Action
  uses: cloudflare/pages-action@v1.5.0
  with:
    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    projectName: prompt-us-pizzeria
    directory: .
