name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # This triggers the script whenever you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cloudflare Pages GitHub Action
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: prompt-us-pizzeria
          directory: .
